- name: variables from inventory
  hosts: frontend

  tasks:
  - name: Printing course information
    ansible.builtin.debug:
      msg: "Hello, i am learning {{ COURSE }}, duration: {{ DURATION }}, Trainer is {{ TRAINER }}"