- name: Insatll packages through loop
  hosts: frontend
  become: yes
  tasks:
  - name: Installing packages through task of loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: present

    loop:
    - nginx
    - mysql
    - zip
