- name: functions or filters in ansible playbook
  hosts: local
  connection: local
  vars:
    persons: "karthikeya, murugan, saravanabava"

  tasks:
  - name: Checking undefined variables
    ansible.builtin.debug:
      msg: "Hello, the undefined variable is:- {{ person | default('karthikeya') }}" #here if person variable is already meantioned means, it takes that, otherwise, it takes default value, which we have mentioned after pipeline is called filter/functions, this is one type only....

  - name: Printing variables
    ansible.builtin.debug:
      msg: " Hello, {{ persons | split(',') }}" # here first, while printing persons it is string , while i have used split(''), with pipeline, it becomes list of persons, cool right...

  - name: Coverting map to list
    vars:
      course:
        name: ansible
        duration: 10hr
        trainer: Sivakumar
    ansible.builtin.debug:
      msg: "Course info:- {{ course | dict2items }}"