- name: shell vs command
  hosts: frontend
  tasks:
  - name: Redirect, ls outpul to a file
    #ansible.builtin.command: "ls -ltr > /tmp/output.txt" [->  here i got the error ]
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result  #The register keyword is used to store the output (result) of a task in a variable for later use in the playbook., where it stores the server details for ex- the output of ["ls -ltr > /tmp/output.txt"] -> directly stores in register keyword, which is command_result is varaiable -> its common thing we can write our varaible no issue...

  - name: print the outcome, which stores in command_result variable inside rersul
    ansible.builtin.debug:
      msg: " {{ command_result }}"
      
