- name: create aws servers and upadte in the route 53 records
  hosts: local
  connection: local
  vars:
    instances: # list of instances
    - mysql
    - backend
    - frontend
    subnet_id: subnet-0a8777752f9125a3e
    sg_id: sg-0d8d7189bee7912bc
  tasks:
  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Environment: testing
    loop: "{{ instances}}"
    register: ec2_output  # the output created instance will be stored in register variable

  - name: printing ec2_output in register variable
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: Creates r53 records [Add new.foo.com as an A record with 3 IPs and wait until the changes have been replicated]
    amazon.aws.route53:
      state: present
      zone: muruga.site
      record: "{{ item.item }}.{{ zone }}" #mysql.muruga.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true # if exited mysql ip address is there means, it ll update with new ip
    loop: "{{ ec2_output.results }}"
